FROM node:22-alpine

WORKDIR /app

RUN npm install -g @angular/cli@latest

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 4200

ENV CHOKIDAR_USEPOLLING=true

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000", "--disable-host-check", "--proxy-config", "proxy.conf.docker.json"]
