FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY DashboardDevops.sln .
COPY src/DashboardDevops.Domain/DashboardDevops.Domain.csproj src/DashboardDevops.Domain/
COPY src/DashboardDevops.Application/DashboardDevops.Application.csproj src/DashboardDevops.Application/
COPY src/DashboardDevops.Infrastructure/DashboardDevops.Infrastructure.csproj src/DashboardDevops.Infrastructure/
COPY src/DashboardDevops.Api/DashboardDevops.Api.csproj src/DashboardDevops.Api/

RUN dotnet restore

COPY . .

EXPOSE 5000

ENV ASPNETCORE_URLS=http://+:5000
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

ENTRYPOINT ["dotnet", "watch", "run", "--project", "src/DashboardDevops.Api", "--non-interactive"]
